leftnav:
- identifier: b6c8c090-d707-9126-837f-7dda4af627c7
  name: Syllabus
  url: /pages/onlinecourse
  weight: 10
- identifier: 2c792bd7-4590-5d33-6e50-77b0ae1237e1
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: external-40914dc7fd694bc7b5d7f9ac3853f324
  name: Online Publication
  url: https://biology.mit.edu/undergraduate/current-students/subject-offerings/covid-19-sars-cov-2-and-the-pandemic/
  weight: 1000
